---
ID: "2ba0793f-abaa-492f-b73e-fb3e42aa7d5f"
Parent: "96f5676b-4515-4046-a962-1c62253be1ad"
Template: "96f5676b-4515-4046-a962-1c62253be1ad"
Path: /sitecore/templates/TAC/Common/Base/Base Navigation/__Standard Values
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20160425T112029Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
