---
ID: "e2fc08c9-9393-4429-8705-74baba64a777"
Parent: "c1177c0b-769b-4b86-ad27-265782df7a7f"
Template: "c1177c0b-769b-4b86-ad27-265782df7a7f"
Path: /sitecore/templates/TAC/Careers/Home Page/__Standard Values
DB: master
SharedFields:
- ID: "1172f251-dad4-4efb-a329-0c63500e4f1e"
  Hint: __Masters
  Type: TreelistEx
  Value: "{A3746154-D2BE-4D9F-95DE-2C5D75FAF48A}"
- ID: "ca9b9f52-4fb0-4f87-a79f-24dea62cda65"
  Hint: __Default workflow
  Value: "{A5BC37E7-ED96-4C1E-8590-A26E64DB55EA}"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "04bf00db-f5fb-41f7-8ab7-22408372a981"
      Hint: __Final Renderings
      Type: Layout
      Value: |
        <r xmlns:xsd="http://www.w3.org/2001/XMLSchema">
          <d
            id="{FE5D7FDF-89C0-4D99-9AA3-B5FBD009C9F3}"
            l="{B9542681-CA29-4A7C-98AC-6E21CC77DB20}">
            <r
              uid="{100EDA93-7F1A-43F8-A314-BD1FB2828F67}"
              ds="{B8F40EDB-A130-44A3-8275-6CA9C00D09A8}"
              id="{E2E3E44E-A330-4094-8A80-200A9736C593}"
              par=""
              ph="/mainContent/columnContent" />
            <r
              uid="{6B646DCB-56B6-4FB8-85AC-98EBAE9E1B57}"
              ds="{7EC4EDDA-F189-41D4-9C41-4FFA7712ABFF}"
              id="{AC2A2F97-74E2-46C8-917B-24AB8E699E55}"
              par="Title=%7BEA3043F6-613B-4DA8-9389-3D7A96B6BE18%7D&amp;Appearance=%7BE3047EE9-38E0-4E8F-AAB3-54014EDF64A4%7D"
              ph="/mainContent/columnRight" />
            <r
              uid="{9E32FB9A-E0BE-4334-A558-54A6157B4A38}"
              id="{37D1B2F2-5521-4E3C-9E22-AC6F17783A84}"
              ph="mainContent" />
            <r
              id="{7EBA9237-D27F-4532-A1A8-4A77659EFDD6}"
              ph="headerNavigation"
              uid="{26BB80CB-CAA2-45FA-BF10-15DA00390634}" />
            <r
              id="{19B266AA-1D31-44AF-AA98-40E224369C55}"
              ph="headerContent"
              uid="{FE4156D4-27C5-4CC4-AF64-B8B3C8C09B1A}" />
            <r
              id="{C34CB96D-8AE0-4E4C-849B-0AFB6AC21D89}"
              ph="headerContent"
              uid="{0C32731B-5423-422B-9B02-B3857D9554C2}" />
            <r
              ds="{C40EA54D-3DC6-4064-A40A-E0A63061231E}"
              id="{B9A9EA5D-A50D-4377-8C33-6EDA1D65C021}"
              par=""
              ph="footerContent"
              uid="{1A311AEC-5D0E-4C84-AE0F-C32ABDB80BA9}" />
            <r
              id="{90E323C8-8503-4950-81C1-C9BB983159C3}"
              ph="footerContent"
              uid="{D126CCE0-9211-4D2A-B674-E3DE261E5E33}" />
          </d>
        </r>
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20160425T111512Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
    - ID: "648581f5-0b1b-40c7-ad1a-5991fb630da3"
      Hint: RobotsFollow
      Type: Checkbox
      Value: 0
    - ID: "68acbb05-02b9-451d-a85c-71074db5d8d7"
      Hint: RobotsIndex
      Type: Checkbox
      Value: 0
