---
ID: "29b048bd-203d-4c87-ba27-6ea55d4707ce"
Parent: "fef3695b-4534-4a3f-b9fb-c7fa65bf79ad"
Template: "fef3695b-4534-4a3f-b9fb-c7fa65bf79ad"
Path: /sitecore/templates/TAC/Events/Content Page/__Standard Values
DB: master
SharedFields:
- ID: "1172f251-dad4-4efb-a329-0c63500e4f1e"
  Hint: __Masters
  Type: TreelistEx
  Value: "{FEF3695B-4534-4A3F-B9FB-C7FA65BF79AD}"
- ID: "f1a1fe9e-a60c-4ddb-a3a0-bb5b29fe732e"
  Hint: __Renderings
  Type: layout
  Value: |
    <r>
      <d
        id="{FE5D7FDF-89C0-4D99-9AA3-B5FBD009C9F3}"
        l="{8F4303CD-8B38-4F23-BA02-DE01AD4A75FC}" />
    </r>
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20170210T010317Z
