---
ID: "5ad19c11-f772-4bf8-8258-0612902e696f"
Parent: "e78d0287-4554-49ac-ae9b-43f303d524e6"
Template: "e78d0287-4554-49ac-ae9b-43f303d524e6"
Path: /sitecore/templates/TAC/Common/Repository Items/Background Themes/__Standard Values
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20160428T191029Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
