---
ID: "bf3034b9-a668-4c4b-bfdf-cd92d98a465e"
Parent: "87a8ab4d-15ab-471b-8096-8f9ffcd1c88c"
Template: "e269fbb5-3750-427a-9149-7aa950b49301"
Path: /sitecore/templates/TAC/Common/Base/Base Meta Information/Meta
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20160425T111934Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
